---
skip-check: 
  - CKV_TF_1 # "Ensure Terraform module sources use a commit hash"
  - CKV_AWS_18 # "Ensure the S3 bucket has access logging enabled"
  - CKV_AWS_144 # "Ensure that S3 bucket has cross-region replication enabled"
# Don't report passed checks in output
quiet: true