---
skip-check:
  - CKV_TF_1 # "Ensure Terraform module sources use a commit hash"
  - CKV_AWS_18 # "Ensure the S3 bucket has access logging enabled"
  - CKV_AWS_144 # "Ensure that S3 bucket has cross-region replication enabled"
  - CKV2_AWS_62 # "Ensure S3 buckets should have event notifications enabled"
  - CKV2_AWS_61 # "Ensure that an S3 bucket has a lifecycle configuration"
  - CKV_AWS_21 # "Ensure all data stored in the S3 bucket have versioning enabled"
  - CKV_AWS_145 # "Ensure that S3 buckets are encrypted with KMS by default"
# Don't report passed checks in output
quiet: true
