---
name: Docker Image CI

on:
  push:
    branches: [releases/**]
    paths: 
      - '.github/workflows/docker-build.yml'
      - 'website/*'
      - '!website/*.md'

jobs:
  Container Registration:
    uses: TheBatchelorFamily/SharedGHA/.github/workflows/container_registration.yml@container_registration
    with:
      containerDirectory: 'website/'
      containerName: 'portfolio_website'
      containerRepo: secrets.DOCKER_USER
      containerVersion: ${{ github.ref }}
    secrets: inherit