---
name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  Container_Registration:
    uses: TheBatchelorFamily/SharedGHA/.github/workflows/container_registration.yml@container_registration
    with:
      containerDirectory: 'website/'
      containerName: 'portfolio_website'
      containerRepo: 'fiercekitti'
      containerVersion: ${{ github.ref }}
    secrets: inherit
