---
name: Terraform Deploy

on:
  push:
    branches: [main]
    paths:
    - infrastructure/*
    - .github/workflows/terraform-deploy.yml
    paths-ignore: [ 'infrastructure/*.md' ]
  workflow_dispatch:

jobs:
  Terraform_Deploy:
    uses: TheBatchelorFamily/SharedGHA/.github/workflows/terraform_deploy.yml@main
    with:
      checkoutBranch: main
      workingDirectory: ./infrastructure/
    secrets: inherit
